# Generated by Django 5.2.13 on 2026-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resultapp", "0005_cart_order_orderitem_delete_buyerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pharmacy_name", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="pharmacy/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="medicine",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
