# Generated by Django 5.2.13 on 2026-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resultapp", "0006_pharmacyprofile_remove_order_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PharmacyProfile",
        ),
        migrations.RemoveField(
            model_name="pharmacysettings",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="pharmacysettings",
            name="currency",
            field=models.CharField(default="tk", max_length=10),
        ),
        migrations.AlterField(
            model_name="pharmacysettings",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="pharmacysettings",
            name="tax_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
