# Generated by Django 5.2.13 on 2026-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resultapp", "0007_delete_pharmacyprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_prefix", models.CharField(default="INV-", max_length=20)),
                (
                    "paper_size",
                    models.CharField(
                        choices=[
                            ("80mm", "POS Thermal (80mm)"),
                            ("58mm", "POS Thermal (58mm)"),
                            ("A4", "Standard A4"),
                        ],
                        default="80mm",
                        max_length=10,
                    ),
                ),
                (
                    "terms_conditions",
                    models.TextField(
                        blank=True,
                        default="Goods once sold are not returnable.",
                        null=True,
                    ),
                ),
                (
                    "footer_note",
                    models.TextField(
                        blank=True, default="Thank you for your business!", null=True
                    ),
                ),
                ("show_discount", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
